package com.course.grpcserver.grpc.server;

import java.util.concurrent.atomic.AtomicInteger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.grpc.server.service.GrpcService;

import com.course.central.proto.resiliency.ResiliencyMessage.ResiliencyRequest;
import com.course.central.proto.resiliency.ResiliencyMessage.ResiliencyResponse;
import com.course.central.proto.resiliency.ResiliencyServiceGrpc;
import com.course.grpcserver.grpc.interceptor.ModifyResponseInterceptor;
import com.course.grpcserver.service.ResiliencyService;

import io.grpc.Context;
import io.grpc.Status;
import io.grpc.stub.StreamObserver;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@GrpcService(interceptors = { ModifyResponseInterceptor.class })
public class ResiliencyServiceGrpcServer extends ResiliencyServiceGrpc.ResiliencyServiceImplBase {

    private ResiliencyService resiliencyService;

    public ResiliencyServiceGrpcServer(@Autowired ResiliencyService resiliencyService) {
        this.resiliencyService = resiliencyService;
    }

    @Override
    public void unaryResiliency(ResiliencyRequest request, StreamObserver<ResiliencyResponse> responseObserver) {
        var result = resiliencyService.generateResiliencyResponse(
                request.getMinDelaySecond(), request.getMaxDelaySecond(), request.getStatusCodesList());

        if (result.getStatusCode() != Status.Code.OK.value()) {
            var errorStatus = Status.fromCodeValue(result.getStatusCode())
                    .withDescription("Generated by server")
                    .asRuntimeException();
            responseObserver.onError(errorStatus);
            return;
        }

        var response = ResiliencyResponse.newBuilder()
                .setDummyString(result.getDummyString())
                .build();

        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }

    @Override
    public void serverStreamingResiliency(ResiliencyRequest request,
            StreamObserver<ResiliencyResponse> responseObserver) {
        while (!Context.current().isCancelled()) {
            var result = resiliencyService.generateResiliencyResponse(
                    request.getMinDelaySecond(), request.getMaxDelaySecond(), request.getStatusCodesList());

            if (result.getStatusCode() != Status.Code.OK.value()) {
                var errorStatus = Status.fromCodeValue(result.getStatusCode())
                        .withDescription("Generated by server")
                        .asRuntimeException();
                responseObserver.onError(errorStatus);
                return;
            }

            var response = ResiliencyResponse.newBuilder()
                    .setDummyString(result.getDummyString())
                    .build();
            responseObserver.onNext(response);
        }

        log.info("Client cancelled request");
    }

    @Override
    public StreamObserver<ResiliencyRequest> clientStreamingResiliency(
            StreamObserver<ResiliencyResponse> responseObserver) {
        return new StreamObserver<>() {

            private final AtomicInteger count = new AtomicInteger(0);

            @Override
            public void onNext(ResiliencyRequest request) {
                var result = resiliencyService.generateResiliencyResponse(
                        request.getMinDelaySecond(), request.getMaxDelaySecond(), request.getStatusCodesList());

                if (result.getStatusCode() != Status.Code.OK.value()) {
                    var errorStatus = Status.fromCodeValue(result.getStatusCode())
                            .withDescription("Generated by server")
                            .asRuntimeException();
                    responseObserver.onError(errorStatus);
                    return;
                }

                count.incrementAndGet();
            }

            @Override
            public void onError(Throwable t) {
                log.error("Error while reading from client: {}", t.getMessage());
            }

            @Override
            public void onCompleted() {
                responseObserver.onNext(ResiliencyResponse.newBuilder()
                        .setDummyString("Received " + count.get() + " requests from client")
                        .build());
                responseObserver.onCompleted();
            }
        };
    }

    @Override
    public StreamObserver<ResiliencyRequest> bidirectionalResiliency(
            StreamObserver<ResiliencyResponse> responseObserver) {
        return new StreamObserver<>() {

            @Override
            public void onNext(ResiliencyRequest request) {
                var result = resiliencyService.generateResiliencyResponse(
                        request.getMinDelaySecond(), request.getMaxDelaySecond(), request.getStatusCodesList());

                if (result.getStatusCode() != Status.Code.OK.value()) {
                    var errorStatus = Status.fromCodeValue(result.getStatusCode())
                            .withDescription("Generated by server")
                            .asRuntimeException();
                    responseObserver.onError(errorStatus);
                    return;
                }

                var response = ResiliencyResponse.newBuilder()
                        .setDummyString(result.getDummyString())
                        .build();
                responseObserver.onNext(response);
            }

            @Override
            public void onError(Throwable t) {
                log.error("Error while reading from client: {}", t.getMessage());
            }

            @Override
            public void onCompleted() {
                responseObserver.onCompleted();
            }
        };
    }

}
